# Generated by Django 6.0.3 on 2026-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepts_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='accepts_stripe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_mode',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery (COD)'), ('online', 'Pay Online')], db_index=True, default='cash_on_delivery', help_text='Choose whether this product is paid on delivery or online.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('other', 'Other')], max_length=20),
        ),
    ]
