# Generated by Django 6.0.3 on 2026-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_accepts_paypal_product_accepts_stripe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='MAD', max_length=10),
        ),
    ]
