# Generated by Django 6.0.3 on 2026-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sitesettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(db_index=True, default=False, help_text='Digital products do not require shipping details from customers.'),
        ),
    ]
