# Generated by Django 6.0.3 on 2026-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_note',
            field=models.CharField(blank=True, help_text='Short promotional text shown below discounted products.', max_length=140),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, upload_to='products/videos/'),
        ),
    ]
