# Generated by Django 6.0.3 on 2026-03-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
